### PR TITLE
Fix version mismatch for skimage

### PR DESCRIPTION
**Pull request by fotisk07**

### CODE REVIEW

**Comment by lcswillems** [comment]
Thank you for your PR. I don't get why there is an extra `data.py` file added? Also, why is there this much packages in the `requirements.txt`? Only a few of them are currently required.

**Comment by fotisk07** [comment]
The added data.py is my fault it was my first time PRing to another repo and I got confused. I'm not currently in front of my computer but I'll fix this later todat

**Comment by fotisk07** [comment]
As far as the requirements file is concerned it has a lot of packages because I used Anaconda so if someone wants to reconstruct the exact same config he can run that. I guess some packages are preinstalled in Anaconda, if it bothers you I could do a clean up of the file later today.

**Comment by lcswillems** [comment]
Thank you for the time you took to make this PR!

If you can remove this `data.py` file and only put the required packages in `requirements.txt`, it would be great!

**Pull request closed without merging**
